### ISSUE TITLE
register error returns 201 but has 409 statusCode 

### ISSUE THREAD

**Issue by rockycamacho** [brainspills/ada-framework#1]
I made 2 error calls to register.
1) Email that is not unique
2) Handle that is not unique

network client returned it as a successful response due to it being a 2XX response

Response code: 201
{"message":"User created","user":{"message":"Data validation failed","statusCode":409,"body":{"code":"ConflictError","message":"Data validation failed","details":{"email":["email must be unique"]}}}}

Response code: 201
{"message":"User created","user":{"message":"Data validation failed","statusCode":409,"body":{"code":"ConflictError","message":"Data validation failed","details":{"handle":["handle must be unique"]}}}}

**Comment by brainspills** [comment]
Fixed issue.
